### ISSUE TITLE
Change the SSH port if more than one `okteto up` is active

### ISSUE THREAD

**Issue by rberrelleza** [okteto/remote-kubernetes#101]
**Describe the bug**
Currently, the plugin always uses port 22100 for SSH. This causes collisions when running more than one instance of the plugin at the same time.

**Comment by rberrelleza** [comment]
We should look into picking a random port, or at least keeping track of the active ones so the instance picks a new one.

**Comment by unthought** [comment]
Actually, according to source, this should work:

https://github.com/okteto/remote-kubernetes/blob/master/src/ssh.ts#L6-L8

https://www.npmjs.com/package/get-port#port

Let me check if I can reproduce this, but until then, maybe this can be closed.
