### ISSUE TITLE
allow setting okteto CLI flags in extension settings

### ISSUE THREAD

**Issue by leighhopcroft** [okteto/remote-kubernetes#121]
I'd like to be able to edit the extension settings to for example change the log level used by the `ctrl+shift+p` `Okteto: Up` commands e.g. `-l=debug` to see debug messages.

The UX could be similar to how the vs code Go extension allows you to set build flags:
![image](https://user-images.githubusercontent.com/11697749/96123370-a0551a00-0eea-11eb-9bf4-62928f76f7fc.png)

**Comment by rberrelleza** [comment]
that's a great idea @leighhopcroft !
