### ISSUE TITLE
Get error when doing okteto up

### ISSUE THREAD

**Issue by SteveCurran** [okteto/remote-kubernetes#133]
I am using version 0.20 on windows 10 running Kubernetes in docker desktop.
Remote SSH extension is installed.

When I execute okteto up I receive the following error:

 C:\Users\steve.curran\AppData\Local\Programs\okteto.exe up -f 'c:\AKS Development\AKSGo\ACM\okteto.yml' --remote '22100' --loglevel=verbose
Exception 0xc0000005 0x0 0x7ffc3f910fff 0x21bff2b0000
PC=0x21bff2b0000

syscall.loadsystemlibrary(0xc00004d920, 0xc0000496c0, 0xc0000496c0, 0x20)       
        runtime/syscall_windows.go:136 +0xe7
syscall.LoadDLL(0x26afe26, 0xb, 0xc000084000, 0xc00005c000, 0xc0000d5ac0)       
        syscall/dll_windows.go:81 +0x16a
syscall.(*LazyDLL).Load(0xc0000041a0, 0x0, 0x0)
        syscall/dll_windows.go:245 +0xc8
syscall.(*LazyProc).Find(0xc0000a3b00, 0x0, 0x0)
        syscall/dll_windows.go:300 +0xbf
syscall.(*LazyProc).mustFind(...)
        syscall/dll_windows.go:318
syscall.(*LazyProc).Addr(...)
        syscall/dll_windows.go:327
syscall.GetUserProfileDirectory(0x160, 0xc0000e2340, 0xc0000d5ba0, 0xc0000e2340, 0x21bd9dcb4e0)
        syscall/zsyscall_windows.go:1910 +0x3e
syscall.Token.GetUserProfileDirectory(0x160, 0xc000046ed0, 0x2c, 0x0, 0x0)      
        syscall/security_windows.go:368 +0x8f
os/user.current(0x0, 0x0, 0x0)
        os/user/lookup_windows.go:217 +0x1c7
os/user.Current.func1()
        os/user/lookup.go:15 +0x29
sync.(*Once).doSlow(0x40bae40, 0x2859570)
        sync/once.go:66 +0xf7
sync.(*Once).Do(...)
        sync/once.go:57
os/user.Current(0xc00004f8d0, 0xa, 0x26335d5)
        os/user/lookup.go:15 +0x105
k8s.io/klog.init.1()
        k8s.io/klog@v1.0.0/klog_file.go:58 +0x4b

goroutine 6 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x40bc1a0)
        k8s.io/klog@v1.0.0/klog.go:1010 +0x92
created by k8s.io/klog.init.0
        k8s.io/klog@v1.0.0/klog.go:411 +0xdd
rax     0x7ffc3cd25894
rbx     0x7ffc3cd25892
rcx     0x41
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x0
rsp     0x705e3fefc0
r8      0x0
r9      0x0
r10     0x0
r11     0x97c
r12     0xc000007a
r13     0x0
r14     0x7ffc3cd25894
r15     0x7ffc3f710000
rip     0x21bff2b0000
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Comment by rberrelleza** [comment]
thanks for the report @SteveCurran , we're looking at it. Could you see if you have a C:\Users\steve.curran\.okteto\okteto.log file as well?

**Comment by SteveCurran** [comment]
@rberrelleza sorry for the confusion, this error is a result of "webroot" anti-malware running on the box. Removal of this took care of the problem. Thanks for the follow up. Keep up the great work on this awesome extension.

**Comment by rberrelleza** [comment]
thanks for following up @SteveCurran ! Let us know if you run into other issues, or if you have any feedback or suggestions!
