### ISSUE TITLE
Automatically install extensions on start/connect

### ISSUE THREAD

**Issue by rberrelleza** [okteto/remote-kubernetes#142]
**Is your feature request related to a problem? Please describe.**
I'd like okteto to automatically install extensions on vscode remote

**Additional context**
VSCode supports this, so it might be a question of docs vs implementing it here. further research is needed.

**Comment by yihui-he** [comment]
https://code.visualstudio.com/docs/remote/ssh#_managing-extensions

**Comment by rberrelleza** [comment]
this is supported directly by devcontainers now
