### ISSUE TITLE
`okteto up` command not work with cmd shell

### ISSUE THREAD

**Issue by yfdyh000** [okteto/remote-kubernetes#148]
**Describe the bug**

`invalid argument "'22100'" for "-r, --remote" flag: strconv.ParseInt: parsing "'22100'": invalid syntax` and stopping.

**To Reproduce**
1. Set the "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe", in `settings.json` of VSCode by Settings UI or editing file.
2. Run the `okteto up` in vscode, using F1 hotkey.
4. See error.

**Expected behavior**
Up work fine.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10 21H1

**Comment by rberrelleza** [comment]
@yfdyh000 could you check if the issue still reproduces on 0.3.4? I wasn't able to reproduce the issue, but we did made some changes on the code that handles port management and the terminal.

**Comment by rberrelleza** [comment]
Can you check if this is still happening on 0.4.1?
