### ISSUE TITLE
cmd not found: space in user-profile 

### ISSUE THREAD

**Issue by smerschjohann** [okteto/remote-kubernetes#158]
**Describe the bug**
Okteto Up is not working if the user profile has a space in it.

**To Reproduce**
1. Create a Windows account with a space in it
2. Run Okteto Uo
3. The error appears as shown on the screenshot

**Expected behavior**
The Extension handles spaces in filenames correctlz

**Screenshots**
![image](https://user-images.githubusercontent.com/11621401/133924629-c636572d-2de5-4da9-bca7-4568cc549383.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode 1.60.1
 - Remote Kubernetes 0.3.4

**Comment by rberrelleza** [comment]
Thanks for reporting this, we're looking at it!
