### ISSUE TITLE
Field selector not found

### ISSUE THREAD

**Issue by pnol** [okteto/remote-kubernetes#164]
**Describe the bug**
The "selector" field is not supported in the okteto.yml using the vscode remote extension

 x  Invalid manifest:
    - line 2: field selector not found
    See https://okteto.com/docs/reference/manifest/ for details

When running okteto up from the command line (using the okteto.exe) it works as expected

**To Reproduce**
1.  add a selector to okteto.yml, e.g.:
selector:
  app: vote
2. run okteto up via visualstudio code

**Expected behavior**
The development container get's deployed in the existing deployment or creates a new deployment : *deployment*-okteto

**Desktop (please complete the following information):**
- OS: Windows
- Version vscode: 1.62.2 (latest)
- Version remote-kubernetes: 0.3.4 (latest)

**Comment by rberrelleza** [comment]
Thanks for filing this! This will be fixed on release 0.3.5. We are resolving a couple of pending issues, but should be out in the next couple of days.

**Comment by rberrelleza** [comment]
This is fixed in the 0.4.1 release
