### ISSUE TITLE
Oketeto up not deploying to active context

### ISSUE THREAD

**Issue by alexgeek** [okteto/remote-kubernetes#174]
**Describe the bug**
Hi, I have a dev and prod context in my kube config.
When I switch between dev and prod as the `current-context`, okteto up ignores this and always use the dev cluster.

**To Reproduce**
1. Switch kube contexts (I use `gcloud container clusters get-credentials ...`)
2. Run okteto up
3. Switch again
4. Run okteto up

**Expected behavior**
I expect it to use the active context? 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 20H2

**Comment by alexgeek** [comment]
I see if I run `okteto context` I can switch it manually, can it not be picked up automatically?

**Comment by rberrelleza** [comment]
yes, you're right @alexgeek .  #172 will include a command for that, but we need to do some testing.

**Comment by rberrelleza** [comment]
This is fixed in the 0.4.1 release
