### ISSUE TITLE
Automatically open okteto terminal if Okteto:Up fails

### ISSUE THREAD

**Issue by pchico83** [okteto/remote-kubernetes#19]
**Is your feature request related to a problem? Please describe.**
I wrote the wrong image in the okteto manifests. `Okteto:Up` failed with a general error message, and it was hard to find the source of the issue.

**Describe the solution you'd like**
If `Okteto:Up` fails, the okteto terminal is automatically open and it is clear the error that happened.

**Comment by rberrelleza** [comment]
fixed by #21
