### ISSUE TITLE
"Unexpected token 'up' in expression or statement" when running "okteto up" via vscode

### ISSUE THREAD

**Issue by pnol** [okteto/remote-kubernetes#190]
**Describe the bug**
"Okteto: up" via visual studio code throws error "Unexpected token 'up' in expression or statement." since the latest update.

"Okteto: Set the context for all the Okteto commands" via vscode does work as expected.

When I run the commands directly via a terminal (not via the vscode extensions "..\..\okteto.exe up") it works as expected

**To Reproduce**
1. Run "Okteto: Up" via vscode: ctr-shift-p + "Okteto Up"
2. Error is returned in the terminal (see screenshot)

**Expected behavior**
"up" runs via vscode extension in the same way as via the terminal

**Screenshots**
Working "okteto: set context .. "
![image](https://user-images.githubusercontent.com/86291078/164715938-7734db7f-e059-4d6f-ad85-0779c24888fc.png)

Error "oketeto: up"
![image](https://user-images.githubusercontent.com/86291078/164714599-76251033-77df-4b6f-8136-9488a3486bf9.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version:  v0.4.1 (vscode) / 2.1.0 (okteto)
 - Default terminal: Powershell

**Comment by rberrelleza** [comment]
it seems like the fix we did to handle paths with spaces on UNIX/Linux broke the command on Windows. Thanks for reporting this @pnol . I'm looking for a solution.
