### ISSUE TITLE
The remote window fails to start if `scp` is not installed in the dev image

### ISSUE THREAD

**Issue by rberrelleza** [okteto/remote-kubernetes#199]
**Describe the bug**
The remote-ssh extension is now using SCP to copy the vscode server to the remote dev container. If scp is not available, the command hangs and eventually it fails.
![image](https://user-images.githubusercontent.com/475313/176830483-f74601be-6c30-4f07-8f7e-a17f399348c3.png)

**To Reproduce**
1.  Clone https://github.com/okteto/python-getting-started
2. Execute the `okteto: up` command in VSCode

**Expected behavior**
The remote window should open 

**Additional context**
The current workaround is to install `openssh-client` in the dev file.

**Comment by snowman2** [comment]
Looks like you need to install the SSH server on the remote machine.

References:
- https://code.visualstudio.com/docs/remote/ssh
- https://code.visualstudio.com/docs/remote/troubleshooting#_installing-a-supported-ssh-server

**Comment by snowman2** [comment]
Adding this to the okteto yaml fixed the issue:
```
command: yum update && yum install -y openssh-server && systemctl start sshd.service && systemctl enable sshd.service && bash
```

**Comment by rberrelleza** [comment]
we'll document the requirements for the dev container on the readme instead of injecting files on demand.
