### ISSUE TITLE
"No matching results" for Ctrl-P-"Okteto"after extension install

### ISSUE THREAD

**Issue by drscotthawley** [okteto/remote-kubernetes#200]
**Describe the bug**
Apparently after installing the extension, we're supposed to be able to type "Okteto" and get results such as "up" "down" etc, but all I see is "No matching results"

**To Reproduce**

1. Install VSCode 1.67 on Ubuntu 20, install Remote-SHH extension.
2. Go to Okteto extension page: https://marketplace.visualstudio.com/items?itemName=okteto.remote-kubernetes
2. Copy command "ext install okteto.remote-kubernetes"
3. In VSCode, press Ctrl-P, and paste in the install command & run it.
4. With extension installed, press Ctrl-P again, then start typing "Okteto", and see that it produces "No matching results".

**Expected behavior**
What [the tutorial](https://www.okteto.com/blog/remote-kubernetes-development/) says should happen: ![tutorial image](https://www.okteto.com/blog/remote-kubernetes-development/okteto-up.png) 

**Screenshots**
Can't screenshot because when I press any other key (e.g. to activate screenshot), the Command Palette disappears.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.04
 - Browser [e.g. chrome, safari]  Brave  (Chrome)
 - Version [e.g. 22] ?

**Additional context**

VSCode  Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:23:40.286Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.17.5-76051705-generic

**Comment by rberrelleza** [comment]
@drscotthawley if you open the extension panel, do you see the extension installed?

![image](https://user-images.githubusercontent.com/475313/176931237-4e5e1e39-3973-499b-88f6-599cbdc154d6.png)

**Comment by drscotthawley** [comment]
Yes, I see it as installed.
![2022-07-01_18-57](https://user-images.githubusercontent.com/13925685/176946842-f54340a7-1639-4fb6-84df-c4a0d55d4ba3.png)

**Comment by drscotthawley** [comment]
![image](https://user-images.githubusercontent.com/13925685/176947045-81227392-232d-4b3f-8589-afb43b2ee4f7.png)

**Comment by rberrelleza** [comment]
We haven't been able to replicate this. Is this still happening on newer versions of the extension?

**Comment by drscotthawley** [comment]
I have not made any attempt to try Okteto since then, and am unlikely to get a chance to try. 
I support closing this issue, if you want to.
