### ISSUE TITLE
`okteto up` not working after cli `2.5.0` upgrade

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/remote-kubernetes#205]
**Describe the bug**
A user has reported that `okteto up` from vscode extension had stop working after the cli `2.5.0` upgrade, even though `okteto up` works from the terminal.

There were several issues along the way, but now the issue is that `okteto up` doesn't work with the extension

**Additional context**
[Full thread](https://kubernetes.slack.com/archives/CM1QMQGS0/p1657579097076959)

** OS VERSION **
mac 11.6 big sur

**Comment by rberrelleza** [comment]
Okteto CLI currently doesn't use 2.5.0, it uses 2.4.2 (this is a common misconception because the extension downloads it's own version of the CLI, instead of the installed version). This is [defined here](https://github.com/okteto/remote-kubernetes/blob/main/src/okteto.ts#L24)
