### ISSUE TITLE
Unable to use the extension Cannot read properties of undefined (reading 'track'))

### ISSUE THREAD

**Issue by idogada-akamai** [okteto/remote-kubernetes#219]
**Describe the bug**
Every Okteto command using the extension results in the following error message.
For example, when running `Okteto Up` I get this prompt:
```
Command 'Okteto: Up' resulted in an error (Cannot read properties of undefined (reading 'track'))
```

**To Reproduce**
1. Install the `Remote - Kubernetes` extension
2. Install the `Remote - SSH` extension
3. Try to run one of the Okteto commands

**Expected behavior**
Okteto command to succeed. For example in `Okteto Up`, to connect vscode in the development pod, with file sync working.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6.1
 - Browser: Chrome 108.0.5359.98
 - Remote Kubernetes Version: 0.4.6
 - Remote SSH Version: 0.94
 - VSCode Version: 1.73.1

**Additional context**
When running `okteto up` the from terminal, and connecting via the remote explorer, it'r working. Seems to be an issue with the extension

**Comment by idogdeveleap** [comment]
@rberrelleza After upgrading I got this message:
```
Command 'Okteto: Up' resulted in an error (command 'okteto.up' not found)
```

I tried to-reinstall the extension, same result

**Comment by idogdeveleap** [comment]
https://user-images.githubusercontent.com/121810673/211116407-365e1f41-1bab-4214-8778-47b3d42ad217.mp4

Attaching screen recording of the error I am getting

**Comment by idogdeveleap** [comment]
@rberrelleza Is it expected to be fixed sometime in the near future?

**Comment by idogdeveleap** [comment]
@rberrelleza I tried to debug this locally, it seems to be related to Telemtry. Commenting all relevant code in `extension.ts`, prevent this error from appearing.


I will continue to debug this and update

**Comment by idogdeveleap** [comment]
After some further debugging. I am not sure exactly how and why it happens but I saw that when you run `sentry.init`([source](https://github.com/okteto/remote-kubernetes/blob/15052f7cb3c1aeb78f8547726755f2924ba2be3c/src/telemetry.ts#L71)), a code from the [Dendron](https://marketplace.visualstudio.com/items?itemName=dendron.dendron) extension gets executed and throws the following error:
```
session.update is not a function
```

Disabling Dendron seems to solve the issue. Though I am not sure what happens here 😅

**Comment by rberrelleza** [comment]
This is very interesting. I think the problem might be that sentry is a global property, and there might a collision between both extensions. I'll see if theres'a way to only load sentry in our extension. 

How did you figure this out @idogdeveleap ?

**Comment by idogdeveleap** [comment]
@rberrelleza I cloned the repo and started debugging and diving into each function call until I noticed that the path is no longer from `Okteto`

**Comment by rberrelleza** [comment]
@david9991 are you still hitting the issue with the undefined track property?

**Comment by david9991** [comment]
@rberrelleza No, I am just experimenting 'command okteto.X not found' issue with Telemetry enabled. While I am debugging this I am getting error message 'session.update is not a function'.

**Comment by rberrelleza** [comment]
this is not reproducing on newer versions of sentry and vscode
