### ISSUE TITLE
Terminal on IDE connected to Remote Environment crashes

### ISSUE THREAD

**Issue by jvc5546** [okteto/remote-kubernetes#232]
**Describe the bug**
After using the command from the command palette `Okteto: Up`, and opening the `Terminal > New Terminal` on VSCode, the terminal tries to start up within the IDE but disappears after a few seconds (crashes). This prevents us from running commands within the shell of the development environment.

**To Reproduce**
1. Clone this repo: git@github.com:okteto/vscode-remote-go.git
2. Open it on VSCode.
3. Within VSCode, use the `Okteto: Up` command:
<img width="1070" alt="image" src="https://github.com/okteto/remote-kubernetes/assets/41653402/6fbfed49-3726-494d-9900-e64e4a3e34fd">

4. This should open a new VSCode window running on the Remote Development Environment. Within this window, go to `Terminal > New Terminal` at the top of the window. This will attempt to start a new terminal with some minimal output, but eventually it crashes without allowing for the user to enter any commands:
<img width="1337" alt="image" src="https://github.com/okteto/remote-kubernetes/assets/41653402/53d0635d-a675-424e-a25d-c258bebd8c53">

**Expected behavior**
A terminal should be able to be opened in the Remote Development Environment, and users should be able to run commands from it.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Mac
 - OS: macOS 13.3.1 (22E261)
 - Browser: Chrome
 - VSCode Version: 1.81.1

**Comment by david9991** [comment]
Uncheck this option to solve the problem:

<img width="881" alt="Screenshot 2023-07-17 at 17 14 16" src="https://github.com/okteto/remote-kubernetes/assets/123219/52afdf7e-94bc-4512-a98b-237aef8787e1">

**Comment by rberrelleza** [comment]
Fixed in cli 2.22
