### ISSUE TITLE
Unable to Install in VS Code

### ISSUE THREAD

**Issue by shivanshs9** [okteto/remote-kubernetes#31]
**Describe the bug**
Unable to install "Remote - Kubernetes" extension from VS Code.

Notification Message:
> Unable to install 'okteto.remote-kubernetes' extension because it is not compatible with the current version of VS Code (version 1.37.1).

**To Reproduce**
1. Go to 'okteto.remote-kubernetes' extension from the extension marketplace in VSCode.
2. Click on 'Install'

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version: VS Code 1.37.1

**Comment by rberrelleza** [comment]
@shivanshs9 this extension requires VS Code 1.38 or newer, we'll update the documentation so this is clearer.

**Comment by shivanshs9** [comment]
Got it! Closing this issue then.
