### ISSUE TITLE
The wrong `okteto.yml` is show if there's a remote dev environment already active

### ISSUE THREAD

**Issue by rberrelleza** [okteto/remote-kubernetes#48]
**Describe the bug**
I ran `okteto: up` on an instance of vscode. But instead of getting the `okteto.yml` of the folder that was opened, the file belonged to the folder I had open on a second vs code window.

**Comment by rberrelleza** [comment]
@rlamana: Independent of this issue,  do you think it's worth showing the full path in the dialog as a clue?

**Comment by rlamana** [comment]
Is this about the new dialog to select the`okteto.yml`? As it was implemented I thought we were displaying the full path already, which allows you to decide what manifest to select.

**Comment by rberrelleza** [comment]
> Is this about the new dialog to select the`okteto.yml`? As it was implemented I thought we were displaying the full path already, which allows you to decide what manifest to select.

The new dialog doesn't show the full path, just relative to the repo. 
![image](https://user-images.githubusercontent.com/475313/67695611-95644b00-f962-11e9-9ee6-39b2cdee5e93.png)

**Comment by rlamana** [comment]
True. It uses the current workspace to look for the files. I made it relative because a full path could be too long and confusing. Maybe we could just show one more directory up?
