### ISSUE TITLE
okteto up : wrong command line

### ISSUE THREAD

**Issue by tsv38** [okteto/remote-kubernetes#85]
When using command palette : okteto up
/C/... rather than C:/
/e/... rather than E:/
No quotes around lile path with a spca in it

See screen capture below

PS E:\Mes Documents\_Dev logiciel\vscode-remote-go> /C/Users/tsv38/AppData/Local/Programs/okteto.exe up -f /e/Mes Documents/_Dev logiciel/vscode-remote-go/okteto.yml --remote 22100
/C/Users/tsv38/AppData/Local/Programs/okteto.exe : Le terme «/C/Users/tsv38/AppData/Local/Programs/okteto.exe» n'est pas reconnu comme nom d'applet de commande,    
fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et   
réessayez.
Au caractère Ligne:1 : 1
+ /C/Users/tsv38/AppData/Local/Programs/okteto.exe up -f /e/Mes Documen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (/C/Users/tsv38/...rams/okteto.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rberrelleza** [comment]
@tsv38 could you upload the screen capture you mention on the issue?

**Comment by tsv38** [comment]
![image](https://user-images.githubusercontent.com/11597547/72321193-8bb9cc00-36a3-11ea-9d0c-1a0d9f52fdf3.png)
